export const ARR = [
  "Matthias Schoenaerts",
  "AnnaSophia Robb",
  "Tanner Buchanan",
  "Kim Basinger",
  "Teri Hatcher",
  "Ian Somerhalder",
  "Utkarsh Ambudkar",
  "David Carradine",
  "Wendell Pierce",
  "Owen Teague",
  "Dominic Monaghan",
  "Ned Dennehy",
  "Nancy Meyers",
  "Maximilian Schell",
  "Matthew Labyorteaux",
  "James MacArthur",
  "David Harewood",
  "Hannah Ware",
  "Tyler Mane",
  "Lee J. Cobb",
  "Nicki Minaj",
  "Mary Woronov",
  "John Rubinstein",
  "Matt Adler",
  "Sammy Davis Jr.",
  "Scott Shepherd",
  "Björn Hlynur Haraldsson",
  "Katie Stevens",
  "Jennifer Wenger",
  "Chloe Harris",
];
